name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: {python_version}

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev

      - run: pipenv run isort --diff .
      - run: pipenv run black --check .
      - run: pipenv run mypy --install-types --non-interactive   # install missing stubs mypy in analysis will complain abo
      - run: make analysis
      - run: pipenv run pytest --cov --cov-fail-under=100

  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . -t {{cookiecutter.repo_name}}:test

      - name: Smoke test docker image
        run: |
          docker run --rm {{cookiecutter.repo_name}}:test 10
